.PHONY: config
config:
	echo "TODO: make conf"
	cp -r $(CURDIR)/configsrc/* $(CONFIG)
	vim $(CONFIG)/interfaces
	vim $(CONFIG)/interfaces.d/lan
	vim $(CONFIG)/interfaces.d/wan
	vim $(CONFIG)/dsl-provider
	vim $(CONFIG)/secrets