name: CI for routing 
on:
  push:
    tags: 
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  release_zip:
    strategy:
      matrix:
        os: [18.04]
        wan_mode: [dhcp, pppoe]
        route_num: [single, dual]
    runs-on: ubuntu-latest
    steps:
      - name: pull repo
        uses: actions/checkout@v3
      - name: create zip 
        run: |
          make build OS_VERSION=${{ matrix.os }} WAN_MODE=${{ matrix.wan_mode }} ROUTE_NUM=${{ matrix.route_num }} version=${{ github.ref_name }} 
          make build-testflow version=${{ github.ref_name }}
        shell: bash
      - name: release a new version
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            *.zip
